# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(choices=[('Kentucky Derby', 'Kentucky Derby'), ('Preakness', 'Preakness'), ('Belmont Stakes', 'Belmont Stakes'), ('Breeders Cup Classic', 'Breeders Cup Classic')], default='Kentucky Derby', max_length=100)),
                ('number_of_horses', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='20', max_length=2)),
                ('name_horse_1', models.CharField(default='None', max_length=200)),
                ('name_horse_2', models.CharField(default='None', max_length=200)),
                ('name_horse_3', models.CharField(default='None', max_length=200)),
                ('name_horse_4', models.CharField(default='None', max_length=200)),
                ('name_horse_5', models.CharField(default='None', max_length=200)),
                ('name_horse_6', models.CharField(default='None', max_length=200)),
                ('name_horse_7', models.CharField(default='None', max_length=200)),
                ('name_horse_8', models.CharField(default='None', max_length=200)),
                ('name_horse_9', models.CharField(default='None', max_length=200)),
                ('name_horse_10', models.CharField(default='None', max_length=200)),
                ('name_horse_11', models.CharField(default='None', max_length=200)),
                ('name_horse_12', models.CharField(default='None', max_length=200)),
                ('name_horse_13', models.CharField(default='None', max_length=200)),
                ('name_horse_14', models.CharField(default='None', max_length=200)),
                ('name_horse_15', models.CharField(default='None', max_length=200)),
                ('name_horse_16', models.CharField(default='None', max_length=200)),
                ('name_horse_17', models.CharField(default='None', max_length=200)),
                ('name_horse_18', models.CharField(default='None', max_length=200)),
                ('name_horse_19', models.CharField(default='None', max_length=200)),
                ('name_horse_20', models.CharField(default='None', max_length=200)),
            ],
            options={
                'ordering': ['race_name'],
            },
        ),
    ]
